version: '3.8'

services:
  server:
    build: ./server
    container_name: fullex-server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app       
      - /app/node_modules   
    env_file:
      - ./server/.env
    depends_on:
      - mongodb

  test-server:
    build: ./server
    container_name: fullex-server-test
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - MONGODB_URI=${TEST_MONGODB_URI}
      - NODE_ENV=test
    command: npm run test:e2e
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    depends_on:
      - mongodb
    ports:
      - "8085:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
